backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'category_counts' 
      get 'age_counts'
    end
 end
  resources :login, only: [:index] # ここを追記します

  root 'login#index' # ここを追記します
  get 'login/index' # 自動で設定されたルーティング

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'

  post "/login", to: "login#create"

  post "/sign_up", to: "sign_up#create"
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validate :user_can_only_favorite_one_tweet

  private

  def user_can_only_favorite_one_tweet
    if user.favorites.exists?
      errors.add(:user_id, "は他のツイートにお気に入りを付けています。")
    end
  end

end

backend/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :category, presence: true

  #validate :user_can_only_have_one_post, on: :create

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end

  private

  def user_can_only_have_one_post
    if user.posts.exists?
      errors.add(:user, 'は既にPostを持っています。')
    end
  end

end

backend/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:age])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:gender]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

backend/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post

  def index
    @favorites = current_user.favorites

    render json: @favorites
  end

  def create
    # ユーザーが他の投稿にお気に入りを付けていないか確認
    if current_user.favorites.exists?
      render json: { error: '他の投稿に既にお気に入りを付けています。' }, status: :forbidden
    else
      favorite = @post.favorites.new(user: current_user)
      if favorite.save
        render json: favorite, status: :created
      else
        render json: favorite.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    favorite = @post.favorites.find_by(user: current_user)
    if favorite.destroy
      render json: { message: 'お気に入りを解除しました。' }, status: :ok
    else
      render json: { error: 'お気に入りを解除できませんでした。' }, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

backend/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def create
    #　メールアドレスとパスワードを取得して、認証して、セッションをJsonで返す
    user = User.find_by(email: params[:email])
    if user&.valid_password?(params[:password])
      session[:user_id] = user.id
      render json: { status: :ok, logged_in: true, user: user }
    else
      render status: :unauthorized, json: { status: 401 }
    end
  end
end

backend/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]
  #before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all

    @posts = Post.all.includes(:favorites)

    @posts = Post.includes(:user).all

    @category_counts_by_age = User.joins(:posts)
                                    .group('users.age', 'posts.category')
                                    .count

    @chart_data = @category_counts_by_age.map do |(age, category), count|
      { age: age, category: category, count: count }
    end

    
    render json: @posts
  end

  def new
    @post = Post.new
  end

  def create
    # ユーザーが既にPostを持っているかどうかをチェック
    user = User.find(params[:user_id])
    #if user.posts.exists?
    #  redirect_to posts_path, alert: '1人のユーザーは1つのPostしか作成できません。'
    #else
      @post = user.posts.new(post_params)
      if @post.save!
        #redirect_to @post, notice: 'Postが作成されました。'
        render json: @post, status: :created
      else
        render json: @post.errors, status: :unprocessable_entity
      end
    #end
  end

  def edit
  end

  # 記事を更新するアクション
  def update
    if @post.update(post_params)
      render json: @post, status: :ok
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # 記事を削除するアクション
  def destroy
    @post.destroy
    render json: { message: 'Post was successfully deleted.' }, status: :ok
  end

  def my_posts
    @posts = current_user.posts
  end

  def category_counts
    category_counts = Post.group(:category).count
    render json: category_counts
  end

  def age_counts
    age_counts = User.group(:age).count
    render json: age_counts
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category)
  end

  def authorize_user!
    unless @post.user == current_user
      render json: { error: '他のユーザーの投稿を編集または削除することはできません。' }, status: :forbidden
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

backend/app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  #メールアドレスとパスワード、名前、学年、性別を受け取って、ユーザーを作成するその後ログインしてセッションをJsonで返す
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      render json: { status: :ok, logged_in: true, user: user }
    else
      Rails.logger.error("User creation failed: #{user.errors.full_messages.join(", ")}")
      render json: { status: 401, errors: user.errors.full_messages }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :age, :gender)
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/favorites_helper.rb
module FavoritesHelper
end

backend/app/helpers/login_helper.rb
module LoginHelper
end

backend/app/helpers/posts_helper.rb
module PostsHelper
end

backend/app/helpers/sign_up_helper.rb
module SignUpHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ttb" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/login/index.html.erb
<h1>校則 変更掲示板</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
  <h2> 現在 <%= current_user.name %> さんがログインしています </h2> <!-- ここを追加します -->
  <h4> メールアドレス： <%= current_user.email %> </h4>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>

backend/app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @post, html: { class: "form-container" } do |form| %>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- フォームの開始 -->
  <div class="form-input">
    <!-- タイトルのラベルとテキストフィールドを表示 -->
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>
  <div class="form-input">
    <!-- 内容のラベルとテキストエリアを表示 -->
    <%= form.label :詳細 %>
    <%= form.text_area :content %>
  </div>

  <div class="pulldown-button">
        <%= form.label :カテゴリ %>
        <%= form.select :category, ["身だしなみ", "持ち物", "校外に関すること", "設備に関すること", "その他"] %> 
    </div>

  <div class="button-container">
    <!-- 更新ボタンを表示 -->
    <%= form.submit "更新", class: "link-button" %>
  </div>
<% end %>

backend/app/views/posts/index.html.erb
<h1>校則 変更掲示板</h1>

<div class="button-container">
  <!-- "新しい投稿" ボタンを表示し、新規投稿ページへのリンクを作成します -->
  <%= link_to "校則変更案", new_post_path, class: "link-button" %>
  <%= link_to "自分の投稿", my_posts_path, class: "link-button" %>
</div>

<ul>
  <!-- @posts 変数から取得した各記事に対してループ処理を行います -->
  <% @posts.each do |post| %>
    <li>
    <p>投稿者: <%= post.user.name %></p>
      <h2><%= post.title %></h2>
    <p><%= post.content %></p>
    <p><%= post.category %></p>
    <p><%= post.id %></p>
      <span>
        <small><%= post.created_at %></small>
      </span>
      <div class="edit-delete-wrapper" >
        <!-- 編集ボタンを表示し、対応する記事の編集ページへのリンクを作成します -->
        <%= link_to "編集", edit_post_path(post), class: "link-button" %>
        <!-- 削除ボタンを表示し、対応する記事を削除するためのフォームを作成します -->
        <%= button_to "削除", post_path(post), method: :delete, class: "link-delete-button" %>
      </div>

    
     <% begin %>
        <% if post.favorited?(current_user) %>
          <!-- 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ -->
          <%= button_to post_favorite_path(post, post.favorites.find_by(user: current_user)), method: :delete do %>
          <span style="color:red;">❤︎</span><%= post.favorites.count %>
          <% end %>
        <% else %>
          <!-- 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ -->
          <%= button_to post_favorites_path(post), method: :post do %>
            <span>❤︎</span><%= post.favorites.count %>
          <% end %>
        <% end %>
      <% rescue NoMethodError => e %>
        <p>エラーが発生しました: <%= e.message %></p>
      <% end %>

    </li>
  <% end %>
</ul>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->

    <h2> 現在 <%= current_user.name %> さんがログインしています </h2> <!-- ここを追加します -->
    <h4> メールアドレス： <%= current_user.email %> </h4>
    <h4> 学年： <%= current_user.age %> </h4>
    <h4> 性別： <%= current_user.gender %> </h4>
     <h4> id: <%= current_user.id %> </h4>
    
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>

<%= line_chart @chart_data.group_by { |data| data[:age] }.transform_values { |values| values.group_by { |v| v[:category] }.transform_values { |v| v.sum { |d| d[:count] } } } %>
<h1>校則 変更掲示板</h1>

backend/app/views/posts/my_posts.html.erb
<h1>自分の投稿</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <p>投稿者: <%= post.user.name %></p>
      <h2><%= post.title %></h2>
      <p><%= post.content %></p>
      <p><%= post.category %></p>
      <p><%= post.id %></p>
      <span>
        <small><%= post.created_at %></small>
      </span>
      <div class="edit-delete-wrapper">
        <%= link_to '編集', edit_post_path(post), class: 'link-button' %>
         <%= button_to "削除", post_path(post), method: :delete, class: "link-delete-button" %>
      </div>
    </li>
  <% end %>
</ul>

backend/app/views/posts/new.html.erb
<h1>校則案投稿</h1>

<%= form_with model: @post, html: { class: "form-container" } do |form| %>
  <!-- フォームの開始 -->
  <div class="form-input">
    <!-- タイトルのラベルとテキストフィールドを表示 -->
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>
  <div class="form-input">
    <!-- 内容のラベルとテキストエリアを表示 -->
    <%= form.label :詳細 %>
    <%= form.text_area :content %>
  </div>

  <div class="pulldown-button">
        <%= form.label :カテゴリ %>
        <%= form.select :category, ["身だしなみ", "持ち物", "校外に関すること", "設備に関すること", "その他"] %> 
    </div>
    
  <div class="button-container">
    <!-- 投稿ボタンを表示 -->
    <%= form.submit "投稿", class: "link-button" %>
  </div>
<% end %>